
# we can give either three dots(...) or write pass 
class DataIngestionConfig:
    pass
class DataValidationConfig:...
class DataTransformationConfig:...
class ModelTrainerConfig:...    
class ModelEvaluationConfig:...
class ModelPusherConfig:...

